import os
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import TimeoutException, NoSuchElementException

class YouTubeCookieExtractor:
    def __init__(self):
        self.driver = None
        self.wait = None
        
    def setup_driver(self):
        """Setup Chrome driver for headless operation"""
        chrome_options = Options()
        
        # Essential for Render
        chrome_options.add_argument('--headless=new')
        chrome_options.add_argument('--no-sandbox')
        chrome_options.add_argument('--disable-dev-shm-usage')
        chrome_options.add_argument('--disable-gpu')
        chrome_options.add_argument('--disable-blink-features=AutomationControlled')
        chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
        chrome_options.add_experimental_option('useAutomationExtension', False)
        
        # User agent to avoid detection
        chrome_options.add_argument('--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')
        
        # Performance options
        chrome_options.add_argument('--disable-logging')
        chrome_options.add_argument('--log-level=3')
        chrome_options.add_argument('--silent')
        
        try:
            self.driver = webdriver.Chrome(options=chrome_options)
            self.wait = WebDriverWait(self.driver, 30)
            return True
        except Exception as e:
            print(f"Chrome setup error: {e}")
            return False
    
    def login_to_google(self, email, password):
        """Login to Google account"""
        try:
            # Go to Gmail login
            self.driver.get("https://accounts.google.com/signin/v2/identifier?flowName=GlifWebSignIn&flowEntry=ServiceLogin")
            time.sleep(2)
            
            # Enter email
            email_input = self.wait.until(EC.presence_of_element_located((By.ID, "identifierId")))
            email_input.send_keys(email)
            email_input.submit()
            time.sleep(2)
            
            # Enter password
            password_input = self.wait.until(EC.presence_of_element_located((By.NAME, "Passwd")))
            password_input.send_keys(password)
            password_input.submit()
            time.sleep(3)
            
            return True
        except Exception as e:
            print(f"Login error: {e}")
            return False
    
    def check_2fa_required(self):
        """Check if 2FA is required"""
        try:
            # Check for 2FA input field
            twofa_input = self.driver.find_elements(By.ID, "totpPin")
            if twofa_input:
                return True
            
            # Check for other 2FA indicators
            twofa_text = self.driver.find_elements(By.XPATH, "//*[contains(text(), '2-Step Verification')]")
            if twofa_text:
                return True
                
            return False
        except:
            return False
    
    def submit_2fa_code(self, code):
        """Submit 2FA verification code"""
        try:
            # Find 2FA input field
            twofa_input = self.wait.until(EC.presence_of_element_located((By.ID, "totpPin")))
            twofa_input.send_keys(code)
            
            # Submit
            submit_btn = self.driver.find_element(By.ID, "idvNext")
            submit_btn.click()
            time.sleep(3)
            
            return True
        except Exception as e:
            print(f"2FA error: {e}")
            return False
    
    def goto_youtube(self):
        """Navigate to YouTube to get cookies"""
        try:
            self.driver.get("https://www.youtube.com")
            time.sleep(3)
            return True
        except:
            return False
    
    def extract_cookies_netscape(self):
        """Extract cookies in Netscape format"""
        cookies = self.driver.get_cookies()
        
        netscape = "# Netscape HTTP Cookie File\n"
        netscape = "# https://curl.se/docs/http-cookies.html\n"
        netscape = "# This file was generated by YouTube Cookie Bot\n\n"
        
        for cookie in cookies:
            domain = cookie['domain']
            if not domain.startswith('.'):
                domain = f".{domain}"
            
            include_subdomains = "TRUE"
            path = cookie.get('path', '/')
            secure = "TRUE" if cookie.get('secure', False) else "FALSE"
            expires = int(cookie.get('expiry', 0)) if cookie.get('expiry') else 0
            name = cookie['name']
            value = cookie['value']
            
            netscape += f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"
        
        return netscape
    
    def extract(self, email, password, twofa_code=None):
        """Main extraction method"""
        if not self.setup_driver():
            return {"status": "error", "message": "Failed to setup browser"}
        
        # Login
        if not self.login_to_google(email, password):
            self.driver.quit()
            return {"status": "error", "message": "Login failed. Check email/password"}
        
        # Check for 2FA
        if self.check_2fa_required():
            if not twofa_code:
                self.driver.quit()
                return {"status": "2fa_required", "message": "2FA code needed"}
            
            if not self.submit_2fa_code(twofa_code):
                self.driver.quit()
                return {"status": "error", "message": "Invalid 2FA code"}
        
        # Go to YouTube
        if not self.goto_youtube():
            self.driver.quit()
            return {"status": "error", "message": "Failed to access YouTube"}
        
        # Extract cookies
        cookies = self.extract_cookies_netscape()
        self.driver.quit()
        
        return {"status": "success", "cookies": cookies}
