import os
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

class YouTubeCookieExtractor:
    def __init__(self):
        self.driver = None
        self.wait = None
        
    def setup_driver(self):
        """Setup Chrome driver for Render"""
        chrome_options = Options()
        
        # Critical for Render
        chrome_options.add_argument('--headless=new')
        chrome_options.add_argument('--no-sandbox')
        chrome_options.add_argument('--disable-dev-shm-usage')
        chrome_options.add_argument('--disable-gpu')
        chrome_options.add_argument('--disable-software-rasterizer')
        chrome_options.add_argument('--disable-blink-features=AutomationControlled')
        chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
        chrome_options.add_experimental_option('useAutomationExtension', False)
        
        # User agent
        chrome_options.add_argument('--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36')
        
        # Find Chrome binary path
        chrome_paths = [
            '/usr/bin/chromium',
            '/usr/bin/chromium-browser',
            '/usr/bin/google-chrome',
            '/usr/bin/google-chrome-stable'
        ]
        
        chrome_bin = None
        for path in chrome_paths:
            if os.path.exists(path):
                chrome_bin = path
                break
        
        if chrome_bin:
            chrome_options.binary_location = chrome_bin
            print(f"✅ Chrome found at: {chrome_bin}")
        else:
            print("⚠️ Chrome not found, trying default")
        
        # Setup service
        try:
            self.driver = webdriver.Chrome(options=chrome_options)
            self.wait = WebDriverWait(self.driver, 30)
            print("✅ Chrome driver started successfully")
            return True
        except Exception as e:
            print(f"❌ Chrome setup error: {e}")
            return False
    
    # Rest of the methods remain same...
    def login_to_google(self, email, password):
        try:
            self.driver.get("https://accounts.google.com/signin/v2/identifier")
            time.sleep(3)
            
            email_input = self.wait.until(EC.presence_of_element_located((By.ID, "identifierId")))
            email_input.send_keys(email)
            email_input.submit()
            time.sleep(2)
            
            password_input = self.wait.until(EC.presence_of_element_located((By.NAME, "Passwd")))
            password_input.send_keys(password)
            password_input.submit()
            time.sleep(3)
            
            return True
        except Exception as e:
            print(f"Login error: {e}")
            return False
    
    def check_2fa_required(self):
        try:
            twofa_input = self.driver.find_elements(By.ID, "totpPin")
            if twofa_input:
                return True
            return False
        except:
            return False
    
    def submit_2fa_code(self, code):
        try:
            twofa_input = self.wait.until(EC.presence_of_element_located((By.ID, "totpPin")))
            twofa_input.send_keys(code)
            submit_btn = self.driver.find_element(By.ID, "idvNext")
            submit_btn.click()
            time.sleep(3)
            return True
        except Exception as e:
            print(f"2FA error: {e}")
            return False
    
    def goto_youtube(self):
        try:
            self.driver.get("https://www.youtube.com")
            time.sleep(5)
            return True
        except Exception as e:
            print(f"YouTube error: {e}")
            return False
    
    def extract_cookies_netscape(self):
        cookies = self.driver.get_cookies()
        
        netscape = "# Netscape HTTP Cookie File\n"
        netscape += "# https://curl.se/docs/http-cookies.html\n"
        netscape += "# Generated by YouTube Cookie Bot\n\n"
        
        for cookie in cookies:
            domain = cookie['domain']
            if not domain.startswith('.'):
                domain = f".{domain}"
            
            include_subdomains = "TRUE"
            path = cookie.get('path', '/')
            secure = "TRUE" if cookie.get('secure', False) else "FALSE"
            expires = int(cookie.get('expiry', 0)) if cookie.get('expiry') else 0
            name = cookie['name']
            value = cookie['value']
            
            netscape += f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n"
        
        return netscape
    
    def extract(self, email, password, twofa_code=None):
        print("🔧 Setting up driver...")
        if not self.setup_driver():
            return {"status": "error", "message": "Browser setup failed"}
        
        print("🔐 Logging in...")
        if not self.login_to_google(email, password):
            self.driver.quit()
            return {"status": "error", "message": "Login failed. Check email/password"}
        
        if self.check_2fa_required():
            if not twofa_code:
                self.driver.quit()
                return {"status": "2fa_required", "message": "2FA code needed"}
            
            print("🔢 Submitting 2FA...")
            if not self.submit_2fa_code(twofa_code):
                self.driver.quit()
                return {"status": "error", "message": "Invalid 2FA code"}
        
        print("📺 Going to YouTube...")
        if not self.goto_youtube():
            self.driver.quit()
            return {"status": "error", "message": "Failed to access YouTube"}
        
        print("🍪 Extracting cookies...")
        cookies = self.extract_cookies_netscape()
        self.driver.quit()
        
        return {"status": "success", "cookies": cookies}
